### PR TITLE
Add xml signature to HTTP POST AuthnRequest

### PR DESCRIPTION
**Pull request by tmoiron**
As per SAML RFP, the signature in a HTTP-POST have to be included inside the xml.

### CODE REVIEW

**Comment by markstos** [comment]
When you say "per SAML RFP", please provide a specific link or section reference to the section being implemented or corrected. 

Thanks for the contribution. 

Note there are recent changes to support multiple AuthnRequests which may impact this work.

**Comment by markstos** [comment]
@tmoiron Since it appears you are increasing our spec-compliance, your contribution is welcome here

**Comment by joedjc** [comment]
@tmoiron @markstos Many thanks for doing this it will be really useful. Something we have noticed is that at the moment it is generating the signature at the end of the SAML request, but to comply with SAML schema the Signature needs to be the second element in the request. The services we've tested on are strict on this and reject the request. Otherwise this seems to be working well for logging in. From what I can tell it is not possible to use HTTP-POST binding for sign out at the moment?

**Comment by markstos** [comment]
I believe #206 is a competing pull request that fulfills this goal was merged. If there's some interest from this PR which remains un-addressed by the other PR, leave a comment. In the meantime, I'm closing this.

**Pull request closed without merging**
