### PR TITLE
support multiple authnContext

### PR DESCRIPTION
**Pull request by cjbarth**
This addresses issue #181 and supersedes PR #183. Please see those other two entries for context.

### CODE REVIEW

**Comment by markstos** [comment]
Looks good. Thanks. Merging.

QA Log
=======
  *  I confirmed that SAML 2 support multiple authentication contexts. [ref](https://msdn.microsoft.com/en-us/library/ee895365.aspx)

**Comment by cjbarth** [comment]
As soon as this lands I'll update the TypeScript typings for this. Is there any interest in maintaining the typings for this project here?

**Comment by markstos** [comment]
@cjbarth Only if you maintain them. My team plans to adopt the TypeScript in the future, but hasn't currently. The project is changing at a slow rate now, so maintenance to the TypeScript bindings should be infrequent.

**Comment by cjbarth** [comment]
In that case, I'll leave them over at DefinitelyTyped for now.

**Pull request merged**
