### PR TITLE
feat(monorepo): move to monorepo structure, see #373

### PR DESCRIPTION
**Pull request by sibelius**
This is moving the current package to a monorepo structure

### CODE REVIEW

**Comment by markstos** [comment]
Sorry for the massive delay.   This is a necessary large diff that's a bit hard to scan. After setting up the monorepo structure, does it result in one project (for now) in the monorepo or two?  I'm inclined to merge this into a v2 branch.

**Comment by sibelius** [comment]
only 1 package

after being stable, we can start moving to more packages

**Comment by markstos** [comment]
This has been merged into v2 branch: https://github.com/bergie/passport-saml/tree/v2 Closing here.  Thanks!

**Comment by sibelius** [comment]
great

**Comment by sibelius** [comment]
@markstos anything I can do to move on?

**Comment by markstos** [comment]
Sorry for the delay. Rebase this onto the main branch and I'll merge it on the main branch.

**Comment by sibelius** [comment]
merged with master, we may need to fix eslint later on

**Comment by cjbarth** [comment]
@sibelius It seems there are still conflicts. But I would like to make sure that `eslint` isn't one of the problems. What did you discover in `eslint` that may need attention?

**Comment by sibelius** [comment]
@cjbarth feel free to finish this pull request, the eslint broke because it was one config when I started working on this pull request, and then changed to another one

**Comment by markstos** [comment]
Today I rebased this and pushed it here:  https://github.com/bergie/passport-saml/pull/new/feat/monorepo

However, both `yarn test` and `yarn lint` return errors that I don't have to investigate now. 

There's also a related effort going on now in #409 to split the project into an internal and external projects.

If someone wants to look into the issue in the related fork I created, that would be helpful. It would also be helpful to leave a comment here which explains more about how the new structure is intended to work. Assume the contributors here are new to using Lerna.

**Comment by markstos** [comment]
I'm abandoning this in favor of more recent forks to rewrite the project in TypeScript and split out the internal SAML library into a separate project.

**Pull request closed without merging**
