### PR TITLE
Bring-up xml-crypto to 1.4.0

### PR DESCRIPTION
**Pull request by LoneRifle**
This update will pick up the following changes:

yaronn/xml-crypto#171
yaronn/xml-crypto#179
yaronn/xml-crypto#183

### CODE REVIEW

**Comment by markstos** [comment]
@LoneRifle I see you appear to be a commiter for `xml-crypto`. I appreciate the nudge here, but do these changes fix known bugs in `passport-saml`?

**Comment by cjbarth** [comment]
I don't know of any reported bugs to this project that this would fix, however https://github.com/yaronn/xml-crypto/issues/164, which is fixed in this proposed update, covers a scenario that could affect users of this library.

**Comment by cjbarth** [comment]
Side note, it seems the CI build failed because we are specifying testing be done with an out-dated version of Node.

**Comment by markstos** [comment]
@cjbarth That looks like a legit reason to upgrade. I'm bumping this dependency. 

Regarding the CI failures due to old Node.js versions. Are you referring to the .travis.yml file? We bumped the Node.js version is that about a month ago: https://github.com/bergie/passport-saml/blob/master/.travis.yml#L3

**Comment by cjbarth** [comment]
So we did. Consider this closed then.

**Pull request merged**
