### PR TITLE
Support multiple certificates in light of IdP cert rotation. Addresse…

### PR DESCRIPTION
**Pull request by austburn**
…s #189

### CODE REVIEW

**Comment by austburn** [comment]
Curious on thoughts of how this might look.

Some of my thoughts that went into this:
* I didn't want a breaking change, therefore leaving `cert` alone
* I didn't want to introduce type fluidity with allowing `cert` to be an array or string
* I figured a single alternate certificate would do

I think all of the above can be contested but figured this might be a good starting point.

**Comment by austburn** [comment]
@ploer any feedback on this?

**Comment by j00k** [comment]
Is there an official maintainer for this project @bergie ?

**Comment by gabecase** [comment]
@bergie Can we get this merged and released? I know of projects running passport-saml with a fork including @austburn's changes, Im sure other passport-saml consumers would benefit from this change.

**Comment by jaustinpage** [comment]
@bergie any updates on this? We could really benefit from this...

**Comment by markstos** [comment]
Closing this, as alternate solution was implemented in #218

**Pull request closed without merging**
