### PR TITLE
Fix multi saml strategy race conditions

### PR DESCRIPTION
**Pull request by stavros-wb**
https://github.com/bergie/passport-saml/issues/425

### CODE REVIEW

**Comment by gunzip** [comment]
thakn you for this fix ! maybe want to provide a big warning for those still using < 1.3.3 packages from npm ?

**Comment by stavros-wb** [comment]
@gunzip https://github.com/bergie/passport-saml/blob/a2ccde0ccdd802b4b12f2450e55166bf8ab01fab/README.md#configure-strategy-for-multiple-providers

**Comment by gunzip** [comment]
about `< 1.3.3` we should update that when this pr gets merged (to see into which release).
The main problem I see is not that
> a User will authenticate successfully through the wrong IDP
but that any subsequent request which happens concurrently to the login endpoint (not an extreme condition : ) will overwrite the saml client options making the call to authenticate() fail.

**Comment by stavros-wb** [comment]
Yes the simple manifestation of this bug (I agree not an extreme condition) will be an error on a user trying to login, but I don't consider this part of the Readme. There are other open issues as well, that aren't part of the Readme.

The more dangerous manifestation of the bug (which I describe happens under extreme conditions) would be a wrong authentication, a sec vulnerability. 

I think we should document the false positives (more dangerous) and not the false negatives. WDYT?

**Comment by gunzip** [comment]
imho it *should* be considered a vulnerability since any user can DoS the login endpoint preventing any other user to authenticate

**Comment by stavros-wb** [comment]
amended

**Comment by stavros-wb** [comment]
@markstos PTAL

**Comment by markstos** [comment]
Published in 1.3.4.

**Pull request merged**
