### PR TITLE
Update xml-encryption

### PR DESCRIPTION
**Pull request by katagaStyle**
Update xml-encryption

### CODE REVIEW

**Comment by hthetiot** [comment]
+1

**Comment by hthetiot** [comment]
Travis is failing due jshint not the deps update.

**Comment by capaj** [comment]
@katagaStyle  you need to bump node.js version as well, because xml-encryption has upped the required version of node. I've opened the same thing here-https://github.com/bergie/passport-saml/pull/217

so merge either and close the other one.

**Comment by markstos** [comment]
Resolved by 691122e, now on master.

**Pull request closed without merging**
