### PR TITLE
Support redirect for Logout flows

### PR DESCRIPTION
**Pull request by stavros-wb**
• Builds on [#16 Inflating redirect response](https://github.com/bergie/passport-saml/pull/16)
  • Reverts [638ce6e4 accepting redirect as well as post; redirect not verified(638ce6e4e257d99bf1f5b59c2b76f0890744ded9)
  • Implements [
Support HTTP-Redirect binding for IdP to SP SLO](https://github.com/bergie/passport-saml/issues/191)

### CODE REVIEW

**Comment by berzniz** [comment]
I would love to see this merged - did you try it with SLO of OneLogin

**Comment by stavros-wb** [comment]
I had a bug when retrieving the `Issuer` from the `LogoutRequest`. I've tested with SimpleSamlPhp and Onelogin. Although I can't find how to setup OneLogin to include a signature for the `LogoutRequest` to make sure the signature validation works as well.

**Comment by markstos** [comment]
To add review, you could link to the part of the SAML spec that discuss SP SLO and related topics.

I think this will be a nice feature to add, but want to be sure about our spec compliance. 

Thanks.

**Comment by markstos** [comment]
Also could you say more about why the mentioned commit was reverted?

**Comment by markstos** [comment]
@stavros-wb Thanks! I'll look for the revised PR.

**Comment by markstos** [comment]
@stavros-wb I'm thinking of doing a "1.0" release within the next 10 days and could include this revised PR if it's ready.

**Comment by stavros-wb** [comment]
thanks @markstos , rebased and squashed on latest master

**Comment by markstos** [comment]
@stavros-wb This looks good to me. Are they are related updates to the README that need to be made for this?

@cjbarth Any other concerns here before this gets merged?

**Comment by markstos** [comment]
@stavros-wb Also, can you confirm if this is considered a breaking change?

**Comment by cjbarth** [comment]
I don't have any concerns about this, but I also don't have a lot of experience with this. I do feel that a README update is warranted though.

**Comment by stavros-wb** [comment]
@markstos 
> @stavros-wb Also, can you confirm if this is considered a breaking change?

Nope. this is not a breaking change. It supports redirects on Logouts, while right now passport-saml supports only `POST`

@cjbarth 
> I don't have any concerns about this, but I also don't have a lot of experience with this. I do feel that a README update is warranted though.

I don't think a README entry is required. I'm not opposed to it, though. SLO is already supported if the protocol binding is `POST` by providing the callback url to the IDP. changing it to redirect would only require changing the setting on the IDP, no further configuration on SP. 
What do you have in mind for the docs?

**Comment by markstos** [comment]
I think it would be useful to mention in the Logout section of the docs that we support SLO and explicitly mention that we support both POST and Redirect bindings.

**Comment by stavros-wb** [comment]
@markstos I've added a small list regarding SLO in the README file

**Pull request merged**
