### PR TITLE
Issue #267

### PR DESCRIPTION
**Pull request by ehsankhfr**
Fix for issue #267.

The "entrypoint" is checked only for the signed requests. Details:
- Bug fix
- Doc update

### CODE REVIEW

**Comment by markstos** [comment]
This proposed fix does not appear to be spec-compliant. The spec requires that Destination (entryPoint) is required when the request is signed. But this patch [*always* requires entryPoint](https://github.com/ehsankhfr/passport-saml/blob/210ad710b61ff3c50cbb2d54d2ba53308aa4d150/lib/passport-saml/saml.js#L21)

**Comment by markstos** [comment]
For further consideration, rebase this PR on to the current `master` and squash the commits down to a minimal number. There should be no "merge commits" in this branch, and maximum of one commits updating ".gitignore". Thanks.

**Comment by cjbarth** [comment]
If this is a security issue, I wouldn't mind fixing it up. However, I wonder, are we moving to a `lockfile` system with this project as this PR includes?

**Comment by markstos** [comment]
@cjbarth Thanks for your hep with this issue. I think adding a lock file (either package-lock.json or yarn.lock) is a sound idea, but this PR is not the place to do it. The PR doesn't even involve any dependencies!

**Comment by markstos** [comment]
This PR was superseded by #299 which addressed the issue raised here, while addressing the concerns with this pull request. Closing.

**Pull request closed without merging**
